### ISSUE TITLE
pre-Alpha checklist

### ISSUE THREAD

**Issue by matthewgee** [brighthive/data-trust-legal#33]
- [ ] Documentation: Complete README starter template
  - [ ] GitHub repo is public (or documented exception in README)
  - [ ] License exists (MIT License, or other license with documented exception to MIT in README)
- [ ] Tests: Some unit tests written
  - [ ] Setup coverage tools (Coveralls.io + pytest.cov)
  - [ ] Setup continuous integration for unit tests (Circle CI)
  - [ ] Setup integration test tool (Cypress.io)
  - [ ] Setup style checking tool (prettier or flake8)
- [ ] Contribute: Ability for teammate to quickly contribute 
  - [ ] “Getting Started” in README
  - [ ] Docker setup: Dockerfile
  - [ ] Docker setup: docker-compose.yml (or docker-compose-dev.yml)
